import { callGemini, stripFences } from "../gemini";

export type ConformResult = { conforms: boolean; violations: string[] };

/**
 * Port of the "conformer" Agent + "check_if_conforms" Task from
 * transform_csv_to_md_table.py. In the original, this agent's job was purely
 * a formatting/rules check (it never touched the underlying cell values -
 * that's handled separately by the code-based diff in lib/reportData.ts,
 * per your instruction to keep your existing code as the source of truth for
 * correctness and only use this agent for the formatting check).
 *
 * Unlike the analyst -> consultant handoff (which is plain text per your
 * instruction), this agent's output is a pass/fail verdict consumed by route
 * code rather than fed into another agent's prompt, so it's asked to return
 * a small JSON verdict instead of prose. Flagging this since it's a minor
 * deviation from "no JSON anywhere" - happy to change it to a plain
 * text verdict that the route parses instead, if you'd rather.
 */
export async function conformAsciiTableWithLLM(
  llmTable: string,
  maxWidths: Record<string, number>
): Promise<ConformResult> {
  const prompt = `You are playing the role of an AI agent in a two-agent pipeline.

Agent role: PrettyTable Table Conformance Checker
Agent backstory: You are an expert in verifying that ASCII tables are generated using PrettyTable and conform to all visual and formatting requirements.
Agent goal: Given an ASCII table generated by PrettyTable, verify that:
- Pipes (|) separate all columns.
- Dashes (-) are used for horizontal lines.
- All text columns are left-aligned, all numeric columns (AMOUNT) are right-aligned.
- Each column matches the width in maximum_width_of_each_column.
- The table looks like it was generated using PrettyTable (not manual/Markdown formatting).
- No Markdown, no center alignment, no multi-line cells.
If the table fails any rule, list which rules were violated. Else, confirm it conforms.

maximum_width_of_each_column = ${JSON.stringify(maxWidths)}

Table to check:
${llmTable}

Respond with ONLY a JSON object, no markdown fencing, no commentary, in exactly this shape:
{"conforms": true or false, "violations": ["list of specific rule violations, empty array if it conforms"]}`;

  const raw = await callGemini(prompt);
  const cleaned = stripFences(raw);

  try {
    const parsed = JSON.parse(cleaned);
    return {
      conforms: Boolean(parsed.conforms),
      violations: Array.isArray(parsed.violations) ? parsed.violations.map(String) : [],
    };
  } catch {
    // If the conformer didn't return valid JSON, treat it as a failed check
    // rather than silently passing bad output through.
    return { conforms: false, violations: ["Conformer agent did not return parseable JSON."] };
  }
}
